### ISSUE TITLE
Unable to get models list

### ISSUE THREAD

**Issue by LukaszCmielowski** [pmservice/customer-satisfaction-prediction#1]
It looks like there is an issue with getting list of deployed models. Models are not present in the drop down list of sample application. Issue may concern all sample apps that do such get.!

**Comment by kbaron-palucka** [comment]
Per info from 01/24 email thread:
_I noticed that you were one of the major contributors to the WML Customer Satisfaction Prediction sample on Github.  I tried deploying this to my bluemix account to connect to a WML service that I installed today.  I believe that we have verified that there is an issue linking the sample together with recent version of WML service.  Some of my colleagues have this working, but they installed WML several months ago.  We also tried having one of them install a new WML service and they noted that the sample will not display any of the models deployed to the newer version of WML.  I also opened up a support ticket with BlueMix support and they noted the same thing.
The issue we are seeing is that none of the deployed models show up in the Scoring stream pull down:_
![err1](https://cloud.githubusercontent.com/assets/21080796/22325875/94cc6774-e3b0-11e6-986c-ea0576e9c952.png)
_And we see this error in the Customer Satisfaction Prediction application log._
![err2](https://cloud.githubusercontent.com/assets/21080796/22325896/b7732b28-e3b0-11e6-97ae-e43147821a5f.png)

**Comment by kbaron-palucka** [comment]
Per info from 01/25 email:
_I am just trying to get the sample stream provided on the Github site.  I have included some screen captures below.  I opened a ticket with BlueMix tech support and they verified that a newly provisioned WML service will not work with the Customer Satisfaction sample provided.  They saw the same error that I put in the screen capture in my email last night.  According to several other people that I work with who have had this working, I have done everything right.  Yet I still get an error in the Sample application when I try to access the pulldown list of available streams.  It points to a specific line in the pm_client.js file.
Please let me know if I am doing something incorrect.
Below is a screen capture of the stream that I downloaded from Customer Satisfaction sample Github site.  I dropped it into my WML service:_
![err3](https://cloud.githubusercontent.com/assets/21080796/22325974/2fe5e942-e3b1-11e6-901b-bc97a42baab6.png)
_This screen capture shows where I got the sample stream file:_ 
![err4](https://cloud.githubusercontent.com/assets/21080796/22326003/5095f52e-e3b1-11e6-9f78-e4a8a61a2eb9.png)

**Comment by yoowoo** [comment]
The service credentials _url_ has changed and sample application needs to add _/pm/v1_ to the retrieved _url_.
