### ISSUE TITLE
Incorrect URL endpoints in pm_client

### ISSUE THREAD

**Issue by ghost** [pmservice/customer-satisfaction-prediction#2]
In my provisioned watson ml service on bluemix, credentials are : "url": "https://ibm-watson-ml.mybluemix.net"

If I look at the api - http://watson-ml-api.mybluemix.net/ - paths begin /v2/...

But in pm_client.js, all requests are appended with '/pm/v1'

**Comment by yoowoo** [comment]
This sample application uses _Machine Learning service API for IBM SPSS Modeler models_ (https://console.ng.bluemix.net/docs/services/PredictiveModeling/pm_service_api_spss.html), which maps to **v1**

http://watson-ml-api.mybluemix.net/ describes _Machine Learning service API for Spark models_, which maps to **v2**

I've modified readme links to directly point to the API used by application.
