### ISSUE TITLE
Watson Machine Learning examples not working

### ISSUE THREAD

**Issue by PhilippeComte** [pmservice/customer-satisfaction-prediction#3]
Hello I have tried the 2 out of the 4 for examples and they are not working properly.
For example the one about Drug selection for treating heart problems, does not allow for scoring the sample patient (even though the UI is displayed) 
Can you help ?

**Comment by yoowoo** [comment]
Hi @PhilippeComte, please open issues under appropriate project.

As for Drug selection application, did you follow the instructions from https://github.com/pmservice/drug-selection? It is crucial to set the expected _contextID_ and my guess is either your application was not binded to the ML service or the model was not uploaded with expected _contextID_.
